### ISSUE TITLE
Spatial-Temporal Aware Graph Construction

### ISSUE THREAD

**Issue by laibajiu** [yash-jakhmola/w-dstagnn#1]
Hi author, can you share the generated Spatial-Temporal Aware Graph Construction?

**Comment by yash-jakhmola** [comment]
You can generate the STAG by executing ./data/STAG_gen.py

**Comment by laibajiu** [comment]
I have limited computing resources and generation takes a long time, can you share?

**Comment by yash-jakhmola** [comment]
Hi, I have added the STAG and STRG graphs in the data folder.

**Comment by laibajiu** [comment]
Thank you so much for sharing!
